#!/bin/bash 
#set -eo pipefail

source ../config/cluster.config
source ../config/kubernetes.config
source ../config/utils.sh

announce "Deleting Conjur Followers."

set_namespace $CONJUR_NAMESPACE_NAME

echo "Deleting Follower pods."
$CLI delete deployment/conjur-follower --force=true
$CLI delete svc/conjur-follower --force=true

echo "Deleting server-certificate config map."
$CLI delete --ignore-not-found cm $CONJUR_CONFIG_MAP

echo "Deleting cluster roles, role bindings and service accounts."
$CLI delete --ignore-not-found clusterrole conjur-authenticator-$CONJUR_NAMESPACE_NAME
$CLI delete --ignore-not-found rolebinding conjur-authenticator-role-binding-$CONJUR_NAMESPACE_NAME
$CLI delete --ignore-not-found sa conjur
$CLI delete --ignore-not-found sa conjur-cluster

echo "Waiting for Conjur pods to terminate..."
while [[ "$($CLI get pods 2>&1)" != "No resources found." ]]; do
  echo -n '.'
  sleep 3
done 
echo

echo "Followers deleted."
