#!/bin/bash 
set -eo pipefail

source ../config/kubernetes.config
source ../config/utils.sh

set_namespace $TEST_APP_NAMESPACE_NAME

if ! [ "${DOCKER_EMAIL}" = "" ]; then
  announce "Deleting image pull secret."
    
  kubectl delete --ignore-not-found secret dockerpullsecret
fi

announce "Deleting test app/sidecar deployment."
$cli delete --ignore-not-found \
  deployment/test-app-summon-sidecar \
  service/test-app-summon-sidecar \
  serviceaccount/test-app-summon-sidecar

announce "Deleting test app/init container deployment."
$cli delete --ignore-not-found \
  deployment/test-app-summon-init \
  service/test-app-summon-init \
  serviceaccount/test-app-summon-init

echo "Waiting for pods to terminate"
until [[ "$($cli get pods 2>&1)" == "No resources found." ]]; do
  sleep 4
  echo -n '.'
done
echo

echo "Test app deleted."
